# SITE CONFIGURATION
baseurl: ""
favicon: assets/favicon.ico                             # Icon displayed in the tab

reveal:
  title: "OSM basics"
  transition: "slide" # none/fade/slide/convex/concave/zoom
  theme: "black" # beige/blood/league/moon/night/serif/simple/sky/solarized/white
  number: true
  numberType: "c" # "h.v" / "h/v" / "c/t"

# Slides
collections:
  slides:
    output: true
    permalink: /:collection/:name
  basements:
    output: true
    permalink: /:collection/:name

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea"]
